version: "3.11"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./db.sqlite3:/app/db.sqlite3
    command: sh -c "python manage.py runserver 0.0.0.0:8000"

